### PR TITLE
Responsive artical #6

### PR DESCRIPTION
**Pull request by MahmoudMH**
make it responsive #6

### CODE REVIEW

**Review by Salam-Dalloul — DISMISSED** [review]

**Review by muhmushtaha — CHANGES_REQUESTED** [review]
if the screen small the background color change and the menu disappear!
@MahmoudMH

**Comment by MahmoudMH** [comment]
@muhmushtaha This is which came with me

**Comment by muhmushtaha** [comment]
fix the conflicts to merge
@MahmoudMH

**Comment by MahmoudMH** [comment]
@muhmushtaha i solved the conflicts

**Review by muhmushtaha — APPROVED** [review]

**Pull request merged**
